import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import http from 'node:http';import {startServer} from '../server.mjs';
test('v1.1 settings keep secrets, task routing and paper/note search scopes',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'paperdesk-v11-api-'));const svc=await startServer({dataDir:dir,port:0});
 const hits=[];const mock=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;hits.push({url:req.url,authorization:req.headers.authorization,body:JSON.parse(body)});res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'OK'}}]}));});await new Promise(r=>mock.listen(0,'127.0.0.1',r));
 t.after(async()=>{await svc.close();await new Promise(r=>mock.close(r));fs.rmSync(dir,{recursive:true,force:true});});
 let cookie='';const request=async(route,method='GET',body)=>{const res=await fetch(svc.url+route,{method,headers:{cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return {status:res.status,data:await res.json()};};
 await request('/api/auth/setup','POST',{username:'接口验收',password:'1'});
 assert.equal((await request('/api/health')).data.version,'1.1.0');
 assert.equal((await request('/api/health')).data.dataDir,dir);
 const initial=(await request('/api/settings')).data;assert.deepEqual(initial.modelConfig.providers,[]);assert.deepEqual(initial.syncProfiles,[]);
 assert.ok(initial.hermes.scriptPath.endsWith('hermes-mcp.mjs'));
 const p=svc.vault.importPdf(Buffer.from('%PDF-1.4\ntest\n%%EOF'),{title:'Paper alpha',chunks:[{page:1,text:'radar paperonly signal'}]}).paper;
 const pdfResponse=await fetch(svc.url+'/api/papers/'+p.id+'/pdf',{headers:{cookie}});assert.equal(pdfResponse.status,200);assert.equal(await pdfResponse.text(),'%PDF-1.4\ntest\n%%EOF');
 svc.vault.saveNote(p.id,'noteterm attached insight');await request('/api/notes','POST',{title:'Research notebook',markdown:'noteterm standalone idea'});
 const papers=(await request('/api/search?q=paperonly&scope=papers')).data.results;assert.ok(papers.length>0);assert.ok(papers.every(x=>x.kind==='paper'));
 const notes=(await request('/api/search?q=noteterm&scope=notes')).data.results;assert.equal(notes.length,2);assert.ok(notes.every(x=>x.kind==='note'));
 assert.equal((await request('/api/search?q=noteterm&scope=papers')).data.results.length,0);
 const config={version:1,providers:[{id:'p1',name:'Test provider',baseUrl:'http://127.0.0.1:'+mock.address().port+'/v1',apiKey:'test-secret-never-public'}],models:[{id:'m1',name:'Answer',model:'test-chat',providerId:'p1',kind:'chat'}],tasks:{answer:'m1',query:'',embedding:''}};
 assert.equal((await request('/api/settings','PUT',{modelConfig:config})).status,200);
 const visible=(await request('/api/settings')).data.modelConfig;assert.equal(visible.providers[0].hasApiKey,true);assert.ok(!JSON.stringify(visible).includes('test-secret'));
 assert.equal((await request('/api/models/test','POST',{config:visible,modelId:'m1'})).status,200);
 assert.equal(hits[0].authorization,'Bearer test-secret-never-public');assert.equal(hits[0].body.model,'test-chat');
 assert.equal((await request('/api/settings','PUT',{modelConfig:visible})).status,200);assert.equal(svc.vault.getSetting('modelConfig').providers[0].apiKey,'test-secret-never-public');
 visible.providers[0].clearApiKey=true;await request('/api/settings','PUT',{modelConfig:visible});assert.equal(svc.vault.getSetting('modelConfig').providers[0].apiKey,'');
 assert.equal((await request('/api/settings','PUT',{syncProfiles:[{id:'bad',name:'Invalid data folder',type:'folder',folderPath:dir}]})).status,400);
 const folderProfile={id:'folder-test',name:'Encrypted folder',type:'folder',folderPath:path.join(dir,'..',path.basename(dir)+'-exchange')};
 assert.equal((await request('/api/settings','PUT',{syncProfiles:[folderProfile]})).status,200);
 assert.equal((await request('/api/sync/status')).data.profiles.length,1);
 const denied=await request('/api/sync/run','POST',{profileId:'folder-test'});assert.equal(denied.data.code,'PAIRING_REQUIRED');
 const wrong=await request('/api/sync/pair','POST',{profileId:'folder-test',username:'接口验收',password:'wrong'});assert.equal(wrong.data.code,'AUTH_FAILED');
 assert.equal(svc.vault.listPapers().length,2);
});